apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        resources:
          requests:
            cpu: "10m"
            memory: "128Mi"
          limits:
            cpu: "20m"
            memory: "256Mi"        
        env:
          - name: SPAN_STORAGE_TYPE
            value: memory
          - name: COLLECTOR_OTLP_ENABLED
            value: 'true'
          - name: COLLECTOR_OTLP_GRPC_HOST_PORT
            value: '0.0.0.0:4317'
          - name: COLLECTOR_OTLP_HTTP_HOST_PORT
            value: '0.0.0.0:4318'
        ports:
          - name: zk-compact-trft
            containerPort: 5775
            protocol: UDP
          - name: config-rest
            containerPort: 5778
            protocol: TCP
          - name: jg-compact-trft
            containerPort: 6831
            protocol: UDP
          - name: jg-binary-trft
            containerPort: 6832
            protocol: UDP
          - name: zipkin
            containerPort: 9411
            protocol: TCP
          - name: c-tchan-trft
            containerPort: 14267
            protocol: TCP
          - name: c-binary-trft
            containerPort: 14268
            protocol: TCP
          - name: grpc-query
            containerPort: 16685
            protocol: TCP
          - name: query
            containerPort: 16686
            protocol: TCP
          - name: admin-http
            containerPort: 14269
            protocol: TCP
          - name: grpc
            containerPort: 14250
            protocol: TCP
          - name: grpc-otlp
            containerPort: 4317
            protocol: TCP
          - name: http-otlp
            containerPort: 4318
            protocol: TCP
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
spec:
  selector:
    app: jaeger
  type: ClusterIP    
  ports:
    - name: admin-query
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: grpc-query
      protocol: TCP
      port: 16685
      targetPort: 16685  
    - name: https-query
      protocol: TCP
      port: 443
      targetPort: 8443

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
spec:
  selector:
    app: jaeger
  type: ClusterIP    
  ports:
    - name: http-zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
    - name: tls-grpc-jaeger
      protocol: TCP
      port: 14250
      targetPort: 14250
    - name: http-c-tchan-trft
      protocol: TCP
      port: 14267
      targetPort: 14267
    - name: http-c-binary-trft
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: admin-http
      protocol: TCP
      port: 14269
      targetPort: 14269
    - name: grpc-otlp
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: http-otlp
      protocol: TCP
      port: 4318
      targetPort: 4318