apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/jaeger:2.11.0
        ports:
          - name: query
            containerPort: 16686
            protocol: TCP
          - name: collector
            containerPort: 4318
            protocol: TCP
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
spec:
  selector:
    app: jaeger
  type: ClusterIP    
  ports:
    - name: query
      protocol: TCP
      port: 16686
      targetPort: 16686

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
spec:
  selector:
    app: jaeger
  type: ClusterIP    
  ports:
    - name: collector
      protocol: TCP
      port: 4318
      targetPort: 4318
